version: '3.8'

services:
  web:
    build: .
    ports:
      - "8050:8050"
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
      - AWS_SESSION_TOKEN=your_session_token
    volumes:
      - .:/app